# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translate_this', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phrases',
            new_name='Phrase',
        ),
    ]
